name: "Build"

on:
  push

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.1'

      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: install dependencies
        continue-on-error: true
        run: |
          brew uninstall --ignore-dependencies openssl && \
          brew install porting/protobuf.rb

      - name: build
        run: make

      - name: Upload to Artifacts
        if: ${{ !github.event.inputs.release_name }}
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output/
